version: 2
updates:
  - package-ecosystem: "git_submodules"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "Sync"
      include: "scope"
